name: Build Dry Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: |
        yarn
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact-${{ matrix.os }}
        path: |
          ${{ matrix.os == 'macos-latest' && './libpg_query/osx/libpg_query.a' || 
             matrix.os == 'ubuntu-latest' && './libpg_query/linux/libpg_query.a' || 
             '' }}
  prepare-and-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        path: downloaded-artifacts
    - name: Prepare artifacts
      run: |
        # move or prepare artifacts
        ls downloaded-artifacts/* 
    # - name: Publish to NPM
    #   run: |
    #     # Assuming you've set up your package.json and .npmrc correctly
    #     npm publish
      # env:
        # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
